### PR TITLE
feature/java sdk

### PR DESCRIPTION
**Pull request by alexbalakirev**

### CODE REVIEW

**Review by vincentdelitz — COMMENTED** [review]
@alexbalakirev general feedback:
- [x] Please update the README.md as well
- [x] When running the build/run command, I'm getting this errror currently:
image

**Comment by alexbalakirev** [comment]
@vincentdelitz  This error was due to SDK not being published. I've published the pre-released version now and it works for me. What should I update in readme? There are no particular changes on this branch that affect the old README. Only that the apiSecret must be also defined in application.properties along with projectId.

**Comment by vincentdelitz** [comment]
> @vincentdelitz This error was due to SDK not being published. I've published the pre-released version now and it works for me. What should I update in readme? There are no particular changes on this branch that affect the old README. Only that the apiSecret must be also defined in application.properties along with projectId.

Replace "web component"  with "UI component" and double check that repo structure is still up to date and yes please add the change with `apiSecret` @alexbalakirev

**Comment by vincentdelitz** [comment]
@alexbalakirev and I'm still getting the same error. Is there something else to change?

**Comment by alexbalakirev** [comment]
@vincentdelitz  That's unusual. I've tried it out on new machine with clean local repository and it worked. The SDK is also accessible  under https://repo.maven.apache.org/maven2/com/corbado/corbado-java/. If it won't work for you, let us make a short video call to see whats wrong.

**Comment by alexbalakirev** [comment]
> Replace "web component" with "UI component" and double check that repo structure is still up to date and yes please add the change with `apiSecret` @alexbalakirev

@vincentdelitz done

**Comment by vincentdelitz** [comment]
> @vincentdelitz That's unusual. I've tried it out on new machine with clean local repository and it worked. The SDK is also accessible under https://repo.maven.apache.org/maven2/com/corbado/corbado-java/. If it won't work for you, let us make a short video call to see whats wrong.

works now!

**Pull request merged**
